---
  - name: Upgrade all packages
    yum: >
      name=*
      state=latest

  - name: Install rpmforge and epel
    yum: >
      name={{ item }}
      state=present
    with_items: repos

  - name: Install dnsmasq/LXC packages
    yum: >
      name={{ item }}
      state=present
    with_items: lxc_packages

  - name: create ifcfg-lxcbr0
    template: >
      src=ifcfg-lxcbr0
      dest=/etc/sysconfig/network-scripts/ifcfg-lxcbr0
  - name: start lxcbr0
    shell: ifup lxcbr0

  - name: append cgroup to fstab
    lineinfile: |
      dest=/etc/fstab
      line="cgroup                  /cgroup                 cgroup  defaults        0 0"
  - name: create cgroup directory
    file: path=/cgroup state=directory
  - name: mount cgroup
    shell: mount -a

  - name: create dnsmasq
    template: >
      src=dnsmasq.conf
      dest=/etc/dnsmasq.conf
  - name: start dnsmasq
    service: name=dnsmasq state=started enabled=yes

  - name: enable forward
    sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes state=present reload=yes

  - name: init iptables
    shell: iptables -F;iptables -t nat -F POSTROUTING;service iptables save

  - name: start iptables
    service: name=iptables state=started enabled=yes
  - name: setting nat
    shell: iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -o eth0 -j MASQUERADE
  - name: save iptables
    shell: service iptables save

  - name: Create directory for centos 6 image chroot
    file: >
      path=/centos6
      state=directory

  - name: Make centos 6 image chroot (may take a while)
    shell: yum --installroot=/centos6 --releasever=6 -y install centos-release rootfiles yum

  - name: copy resolv.conf
    copy: src=/etc/resolv.conf dest=/centos6/etc/

  - name: remove /dev/null
    shell: chroot /centos6/ rm -f /dev/null

  - name: mknod
    shell: chroot /centos6/ mknod -m 666 /dev/null c 1 3;chroot /centos6/ mknod -m 666 /dev/zero c 1 5;chroot /centos6/ mknod -m 666 /dev/urandom c 1 9;chroot /centos6/ ln -s /dev/urandom /dev/random;chroot /centos6/ mknod -m 600 /dev/console c 5 1;chroot /centos6/ mknod -m 660 /dev/tty1 c 4 1;chroot /centos6/ chown root:tty /dev/tty1

  - name: create pts and shm
    shell: chroot /centos6/ mkdir -p /dev/shm;chmod 1777 /dev/shm;mkdir -p /dev/pts;chmod 755 /dev/pts

  - name: install dhclient passwd openssh-server
    shell: chroot /centos6/ yum -y install dhclient passwd openssh-server

  - name: create key
    shell: chroot /centos6/ ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa

  - name: install public key
    shell: cat /root/.ssh/id_rsa.pub > /centos6/root/.ssh/authorized_keys;chmod 400 /centos6/root/.ssh/authorized_keys

  - name: copy network
    template: >
      src=network
      dest=/centos6/etc/sysconfig/network

  - name: copy ifcfg-eth0
    template: >
      src=ifcfg-eth0
      dest=/centos6/etc/sysconfig/network-scripts/ifcfg-eth0

  - name: copy fstab
    template: >
      src=fstab
      dest=/centos6/etc/fstab

  - name: copy lxc-sysinit.conf
    template: >
      src=lxc-sysinit.conf
      dest=/centos6/etc/init/lxc-sysinit.conf


  - name: Setting root password to 'centos' (change this later)
    shell: echo "root:centos" | chroot /centos6/ chpasswd

  - name: disable udev-post
    shell: chroot /centos6/ chkconfig udev-post off

  - name: archive centos6-lxc-root
    shell: cd /centos6 ; tar czvf /centos6-lxc-root.tgz *
